version: '3.8'

services:
  # 1. Database MySQL
  db:
    image: mysql:8.0
    container_name: my-mysql
    ports:
      - "3306:3306"
    environment:
      # Lấy mật khẩu từ file .env
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
      MYSQL_ROOT_HOST: "%"
      MYSQL_AUTHENTICATION_PLUGIN: 'mysql_native_password'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # 2. Backend API (Node.js)
  backend:
    image: huyhoang2609/my-project-backend:latest
    container_name: my-backend
    restart: always
    expose:
      - "3000"
      
    # FIX RACE CONDITION: Sử dụng biến SLEEP_TIME
    command: bash -c "sleep ${SLEEP_TIME} && npm run start" 

    environment:
      # Lấy biến DB và SMTP từ file .env
      DB_HOST: db
      DB_USER: root
      DB_PASS: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_DATABASE_NAME}
      
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      
    depends_on:
      - db
    networks:
      - app-network

  # 3. Frontend React/Nginx
  frontend:
    # Tên Image đã xác nhận từ log CI/CD
    image: huyhoang2609/my-project-frontend:latest
    container_name: my-frontend
    restart: always
    ports:
      - "80:80" # Cổng Web chính
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
